<a href="https://colab.research.google.com/github/mayuresh-tungare/pandas-workout/blob/main/c01-series/ex2-scaling-test-scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

When I was in high school and college, our instructors sometimes gave extremely
hard tests. Rather than fail most of the class, they would scale the test scores, known in
some places as grading on a curve. They would assume that the average test score
should be 80, calculate the difference between our actual mean and 80, and then add
that difference to each of our scores.
For this exercise, I want you to generate 10 test scores between 40 and 60, again
using an index starting with September and ending with June. Find the mean of the
scores and add the difference between the mean and 80 to each of the scores.

In [1]:
#import necessary libraries
import pandas as pd
import numpy as np

In [3]:
# generate 10 test scores between 40 and 60 using an index starting with September and ending with June.
g = np.random.default_rng(0)
s = pd.Series(g.integers(40,60,10))

In [5]:
#use an index starting with September and ending with June.
s.index ='Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()

In [7]:
#Find the mean of the scores
print(f"Mean score: {s.mean()}")
print(f"Difference between mean and 80: {80 - s.mean()}")
print(f"New scores: {s + (80 - s.mean())}")

Mean score: 47.0
Difference between mean and 80: 33.0
New scores: Sep    90.0
Oct    85.0
Nov    83.0
Dec    78.0
Jan    79.0
Feb    73.0
Mar    74.0
Apr    73.0
May    76.0
Jun    89.0
dtype: float64

There’s at least one other way to scale test scores: by looking at both the mean
of the scores and their standard deviation. Anyone who scored within one standard
deviation of the mean got a C (below the mean) or a B (above the mean).
Anyone who scored more than one standard deviation above the mean got an
A, and anyone who got more than one standard deviation below the mean got a
D. During which months did our student get an A, B, C, and D?
 Were there any test scores more than two standard deviations above or below
the mean? If so, in which months?
 How close are the mean and median to each another? What does it mean if they
are close? What would it mean if they were far apart?

In [16]:
# A - Anyone who scored more than one standard deviation above the mean got an A
s[s > (s.mean() + s.std())]

Sep    57
Jun    56
dtype: int64

In [18]:
# B - Anyone who scored within one standard deviation above the mean got a B
s[(s > s.mean()) & (s < (s.mean() + s.std()))]

Oct    52
Nov    50
dtype: int64

In [20]:
# C - Anyone who scored within one standard deviation below the mean got a C
s[(s < s.mean()) & (s < (s.mean() + s.std()))]

Dec    45
Jan    46
Feb    40
Mar    41
Apr    40
May    43
dtype: int64

In [22]:
# D - Anyone who scored less than one standard deviation below the mean got a D
s[s < (s.mean() - s.std())]

Feb    40
Apr    40
dtype: int64

In [25]:
# Were there any test scores more than two standard deviations above or below the mean?
s[(s <(s.mean() - 2*s.std())) | (s > (s.mean() + 2*s.std()))]

Series([], dtype: int64)

In [30]:
# How close are the mean and median to each another? What does it mean if they are close? What would it mean if they were far apart?
print(s.mean())
s.median()

47.0

45.5